### ISSUE TITLE
Want to add features, unclear where to start

### ISSUE THREAD

**Issue by EMCP** [jintoppy/protractor-html-screenshot-reporter#65]
I am a little new to adding features to someone elses code..  So here's my take 

I want a flag to generate a "Master" image set, that I believe reflects the correct screen.. and save it in some folder aside from the test results.

On subsequent passes, when generating the test results.. if this master image set exists (and matches the number of shots to some agreeable number), then perform a stitching or concatenation of the two side by side.  Such that,

Each resulting screenshot is stitched side by side with the master-correct image, on the left.  The new resulting image from the test on the right.

Where can I get started, I can fork the project.. and I guess I'd create a small tester-test suite ?

**Comment by jintoppy** [comment]
1. Fork the project. 
2. Clone the fork and add your functionalities
3. If you think the new functionality is a generally useful one, please create a pull request (PR) also so that it can be merged in this repo

**Comment by EMCP** [comment]
I am knowledgeable about how to fork a repository.  Thank you.  

Where can I research how these plugins / reports work?  In particular with this specific project.
